name: "Microservice Intelligence"
description: "Uses the LeanIX Microservice Intelligence integration to write microservice information to a workspace"
inputs:
  serviceName:
    description: "Name of the microservice within your workspace (defaults to the shortname of your github repository)"
    required: false
    default: ""
  configFilePath:
    description: "Path of the config file describing the microservice"
    required: false
    default: "pivio.yaml"
  additionalMavenParameters:
    description: "Defines parameters that are added to maven calls as a suffix. Use case: Configure maven repo credentials for license scan"
    required: false
    default: ""
runs:
  using: "docker"
  image: "docker://leanix/microservice-intelligence-action:latest"
